labo_home:
    pattern:  /
    defaults: { _controller: AcmeGroupLaboBundle:Labo:index }

labo_commerce:
    pattern:  /commerce
    defaults: { _controller: AcmeGroupLaboBundle:Labo:commerce }

labo_entity_action:
    pattern:  /commerce/{entityName}/{id}/{action}
    defaults: { _controller: AcmeGroupLaboBundle:Labo:entity, id: null, action: 'view' }


