# acme_group_survey:
#     resource: "@AcmeGroupSurveyBundle/Resources/config/routing.yml"
#     prefix:   /

main_home:
    pattern: /{_locale}
    defaults: { _controller: AcmeGroupSiteBundle:Site:home, _locale: %locale% }
    requirements:
        _locale: %default_locales%

# PAGES SITE (public)
acme_site:
    resource: "@AcmeGroupSiteBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: %default_locales%

# PAGES LABO
acme_labo:
    resource: "@AcmeGroupLaboBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/labo
    requirements:
        _locale: %labo_locales%

# USER ROUTING
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile
    requirements:
        _locale: %default_locales%

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    requirements:
        _locale: %default_locales%

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    requirements:
        _locale: %default_locales%

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
    requirements:
        _locale: %default_locales%
