parameters:
    AcmeGroup_bundle.route:    AcmeGroup\services

services:

    ###################################
    ### OUTILS GÉNÉRIQUES
    ###################################

    # Fonctionnalités pour articles
    labobundle.article:
        class: %AcmeGroup_bundle.route%\article
        arguments: [@service_container]

    # Fonctionnalités pour articles
    labobundle.entities:
        class: %AcmeGroup_bundle.route%\entities
        arguments: [@service_container]

