<?php

namespace AcmeGroup\LaboBundle\Entity;

use labo\Bundle\TestmanuBundle\Entity\laboBaseRepository;

/**
 * articleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articleRepository extends laboBaseRepository {

	/**
	* findXArticles
	* Renvoie X ($nb) articles
	*
	* @param int $nb
	*/
	public function findXArticles($nb) {
		$qb = $this->createQueryBuilder('element');
		$qb->leftJoin('element.imagePpale', 'ip')
			->addSelect('ip')
			->leftJoin('element.marque', 'm')
			->addSelect('m')
			->leftJoin('m.logoImage', 'li')
			->addSelect('li');
		$qb = $this->excludeExpired($qb);
		$qb = $this->withVersion($qb);
		$qb = $this->defaultStatut($qb);
		$qb->setMaxResults($nb) // limite le nombre de résultats
			->orderBy('element.plusVisible', 'DESC') // Sélectionne en premier les articles "plus visibles"
			->addOrderBy('element.notation', 'DESC'); // Puis par notation
		return $qb->getQuery()->getResult();
	}

	/**
	* findArtByCategorie
	* Liste des produits d'une catégorie
	*
	* @param string 	$slug de categorie
	*/
	public function findArtByCategorie($params) {
		if(is_string($params)) $slug = array($params);
			else $slug = $params;
		// var_dump($slug);
		//
		$qb = $this->createQueryBuilder('element');
		$qb->join('element.categories', 'c')
			->where($qb->expr()->in('c.slug', $slug));
		// $qb = $this->excludeExpired($qb);
		$qb = $this->withVersion($qb);
		$qb = $this->defaultStatut($qb);
		$qb->leftJoin('element.imagePpale', 'ip')
			->addSelect('ip')
			->leftJoin('element.images', 'ii')
			->addSelect('ii');
		// $qb->groupBy('r'); // regrouper par réseaux
		$qb->orderBy('r.id', 'ASC')
			->addOrderBy('element.prix', 'ASC');
		return $qb->getQuery()->getResult();
	}


}