<?php

namespace AcmeGroup\LaboBundle\Entity;

use labo\Bundle\TestmanuBundle\Entity\typeRepository;

/**
 * cuissonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cuissonRepository extends typeRepository {

	public function defaultVal($defaults = null) {
		// if($defaults === null) $defaults = array("Actif");
		// return parent::defaultVal($defaults);
		return null;
	}

}
