<?php

namespace AcmeGroup\LaboBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Query;

use \Exception;
use \DateTime;

/**
 * downloadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class downloadRepository extends EntityRepository {


}
