<?php

namespace AcmeGroup\LaboBundle\Entity;

use labo\Bundle\TestmanuBundle\Entity\typeRepository;

/**
 * uniteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uniteRepository extends typeRepository {

	public function defaultVal($defaults = null) {
		if($defaults === null) $defaults = array("Pièce");
		return parent::defaultVal($defaults);
	}

}
