<?php

namespace AcmeGroup\LaboBundle\Entity;

use Doctrine\ORM\EntityRepository;
use AcmeGroup\LaboBundle\Entity\baseLaboRepository;
use Doctrine\ORM\QueryBuilder;
use \Exception;
use \DateTime;

/**
 * versionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class versionRepository extends EntityRepository {

	/**
	* defaultVal
	* Renvoie l'instance de la version par défaut (ou null)
	*/
	public function defaultVal($defaults = null, $onlyOneObject = false, $champ = 'nom') {
		return $this->defaultVersion();
	}

	/**
	* defaultVersion
	* Renvoie l'instance de la version par défaut (ou null)
	*/
	public function defaultVersion() {
		$qb = $this->createQueryBuilder('element');
		$qb->where('element.defaultVersion = :true')
			->setParameter('true', 1);
		try {
			$result = $qb->getQuery()->getSingleResult();
		} catch (Exception $e) {
			// printf("Aucun résultat pour la version par défaut…\n");
			$result = null;
		}
		return $result;
	}

}

