<?php

namespace AcmeGroup\LaboBundle\Entity;

use Doctrine\ORM\EntityRepository;
use laboBundle\Entity\baseVersionRepository;
use Doctrine\ORM\QueryBuilder;
use \Exception;
use \DateTime;

/**
 * versionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class versionRepository extends baseVersionRepository {


}

